Использование индексера для поиска в результатах crawler
akekukh/gosearch pull request #2
Opened 2022-03-27 14:09 UTC by akekukh

2022-03-28 10:52 UTC, DmitriyVTitov requested changes
Не использован бинарный поиск, хотя массив документов отсортирован.

2022-03-28 10:52 UTC, DmitriyVTitov commented on task-2/cmd/gosearch.go
> +	}
по условиям задания тут требовалось использовать бинарный поиск

2022-03-28 11:45 UTC, akekukh commented on task-2/cmd/gosearch.go
> +	}
Точно... сорри. Переделал

2022-03-28 13:42 UTC, akekukh commented on task-2/cmd/gosearch.go
> +	}
Просто я думал "Зачем бинарный, я и так знаю где этот элемент в массиве"

2022-03-30 08:44 UTC, DmitriyVTitov approved these changes
ОК

2022-03-30 08:44 UTC, DmitriyVTitov commented on task-2/cmd/gosearch.go
> +	sortDocs(docs)
желательно не злоупотреблять функциями, которые ничего не возвращают
их сложно считывать при использовании, нужно переходит к коду, чтобы понять смысл побочного эффекта

2022-03-31 07:06 UTC, akekukh commented on task-2/cmd/gosearch.go
> +	sortDocs(docs)
Ага, запомню

2022-03-31 07:06 UTC, merged