Сохранение результатов парсинга сайтов в файл
akekukh/gosearch pull request #4
Opened 2022-04-04 08:57 UTC by akekukh

2022-04-05 12:25 UTC, DmitriyVTitov requested changes
io.Reader и io.Writer нигде не используются, а должны.
И ещё: у вас некоторые функции называются существительными (dataSource, Docs), это не принято, функция - глагол.

2022-04-05 14:49 UTC, akekukh commented
Поправил замечания, прошу посмотреть еще раз

2022-04-06 18:34 UTC, DmitriyVTitov approved these changes
ОК

2022-04-06 18:34 UTC, DmitriyVTitov commented on task-5/cmd/gosearch.go
> +		err = nil
`err = nil` - что-то неправильное, так не должно быть.
можно:
```
if err != nil {
  if os.IsNotExists(err) {
    ...
   } else ...
```

2022-04-06 18:34 UTC, DmitriyVTitov commented on task-5/cmd/gosearch.go
> +		docs[i].ID = i
полезно разделять такие блоки пустыми строками, хотя это дело вкуса

2022-04-06 18:34 UTC, DmitriyVTitov commented on task-5/cmd/gosearch.go
> +	hash.Add(docs)
Индекс - большая подсистема нашего приложения, такие вещи следует создавать явно, а не в результате побочного эффекта функции.

2022-04-09 16:03 UTC, akekukh commented on task-5/cmd/gosearch.go
> +		err = nil
Да, согласен. Переделал. Спасибо

2022-04-09 16:03 UTC, merged