Тесты и бенчмарки sort.Ints и sort.Strings
akekukh/gosearch pull request #6
Opened 2022-04-14 07:51 UTC by akekukh

2022-04-15 15:29 UTC, DmitriyVTitov requested changes
Тесты должны писаться по стандарту. Механически.
Используйте генератор IDE.

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +func Test_sortInts(t *testing.T) {
TestSort_Ints - по аналогии с именем теста для метода.
Но это так.

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +	got := []int{74, 59, 238, -784, 9845, 959, 905, 0, 0, 42, 7586, -5467984, 7586}
got - то, что получили. А это входные данные.

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +	data := got
что-то странное

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +		t.Errorf("   got %v", data)
почему ажно две ошибки?

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +	}
Что-то не то.
Должно быть:
```
got := Sort([]int{3,2,1})
want := []int{1,2,3}
if !reflect.DeepEqual(got, want) ...
```
Тут что-то сложное.

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +		{"test3", []string{"", "Hello", "foo", "bar", "foo", "f00", "%*&^*&^&", "***"}},
эти примеры ничем не отличаются
я бы добавил `[]string{}, nil` и т.д.

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +	}{
а где `want`?

2022-04-15 15:29 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +}
должен быть цикл с многократным запуском
1 прогон операции предполагает даёт сильную ошибку измерений

2022-04-15 17:33 UTC, akekukh commented on task-7/sort_test.go
> +		t.Errorf("   got %v", data)
Подсмотрел реализацию в библиотеке стандартной, мне понравилось https://go.dev/src/sort/sort_test.go

2022-04-15 18:05 UTC, akekukh commented on task-7/sort_test.go
> +	data := got
ага) Переделал

2022-04-15 18:05 UTC, akekukh commented on task-7/sort_test.go
> +		t.Errorf("   got %v", data)
Переделал

2022-04-15 18:05 UTC, akekukh commented on task-7/sort_test.go
> +	}
Переделал

2022-04-15 18:06 UTC, akekukh commented on task-7/sort_test.go
> +		{"test3", []string{"", "Hello", "foo", "bar", "foo", "f00", "%*&^*&^&", "***"}},
Добавил

2022-04-15 18:06 UTC, akekukh commented on task-7/sort_test.go
> +	}{
добавил

2022-04-15 18:06 UTC, akekukh commented on task-7/sort_test.go
> +}
Сделал

2022-04-17 12:41 UTC, akekukh commented on task-7/sort_test.go
> +	got := []int{74, 59, 238, -784, 9845, 959, 905, 0, 0, 42, 7586, -5467984, 7586}
переделал

2022-04-17 12:42 UTC, akekukh commented on task-7/sort_test.go
> +func Test_sortInts(t *testing.T) {
Переделал

2022-04-17 19:34 UTC, DmitriyVTitov approved these changes
ok

2022-04-17 19:34 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +	got := array
зачем нужна эта переменная?

2022-04-17 19:34 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +		{"test3", []string{"", "Hello", "foo", "bar", "foo", "f00", "%*&^*&^&", "***"}, []string{"", "%*&^*&^&", "***", "Hello", "bar", "f00", "foo", "foo"}},
лучше писать имена полей, так сложно читать

2022-04-17 19:34 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +			got := input
опять непонятная переменная

2022-04-17 19:34 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +			input := tt.input
ещё одна лишняя

зачем все эти переменные? чем плоха исходная `tt.input`?

2022-04-17 19:34 UTC, DmitriyVTitov commented on task-7/sort_test.go
> +	data := generateRandomIntArray(b.N)
b.N ещё не вычислена, значение b.N зависит от времени выполнения одной итерации и меняется по ходу теста

2022-04-22 07:11 UTC, merged